### ISSUE TITLE
Make chokidar an optional dependency

### ISSUE THREAD

**Issue by jedwards1211** [Macil/flow-copy-source#29]
I guess `flow-copy-source` has some watch commands, but I don't use them, and its old version of `chokidar` depends on an old version of `fsevents` which doesn't build on Node 12.

**Comment by Macil** [comment]
Fsevents itself is an optional dependency of chokidar, so there shouldn't be an issue. The fsevents dependency can fail to install (and will fail on any non-MacOS platform) without causing the install of flow-copy-source or chokidar to fail. Please let me know if you see flow-copy-source failing to install on any current version of Node.

If it can be avoided, I'd rather not have any functionality gated on an optional dependency. If an optional dependency was involved, I'd want it wrapped in something that could provide fallback support to give the functionality when the optional dependency wasn't there. Chokidar is that wrapper that provides fallback support in case fsevents isn't installed.

(The current version of flow-copy-source depends on the latest version of chokidar which optionally depends on the latest version of fsevents, though fsevents only compiles on MacOS.)

**Comment by jedwards1211** [comment]
I see.  Unfortunately it seems like ignoring optional dependencies with yarn isn't very convenient.  In any case I'm out of luck until Babel 8 is released, because `@babel/cli` 7 depends on the old `fsevents`.
